### ISSUE TITLE
Consider change master branch to main branch

### ISSUE THREAD

**Issue by ycAbout** [BrkRaw/bruker#44]
There was a movement in changing the master to main, due to obvious reasons. 

Consider change the master branch to main and delete master branch (Just a little suggestion).

**Comment by dvm-shlee** [comment]
@ycAbout 
Thank you for your suggestion, I will check if I can make it soon.
I'm currently out of date on the git since I was not focused on software development in recent years after putting my efforts into this project. 

I think I really need a collaborator who is familiar with this git stuff which really moving forward fast.
If you are willing to contribute to this project, please let me know!

**Comment by ycAbout** [comment]
Hi @dvm-shlee, 
A little background.
I am a software developer worked with @gdevenyi, and I am currently working on expanding the capacity of LORIS (a research data management software) to handle animal mri data in bids format. In order to do that, we decided to use bruker to convert raw animal mri to bids first. My short term goal within bruker is to make it generate validated bids format. This would benefit bruker quite a bit as well in terms of bids converter capacity. I'm familiar with git enough in this concern. There is some uncertainty for my involvement in bruker after this goal is reached. Please let me know how you feel.

**Comment by dvm-shlee** [comment]
@ycAbout Sorry about delaying on this simple task, just change the default branch to 'main'
