### ISSUE TITLE
[bids output] CogAtlasID should match format "uri", so does CogPOID

### ISSUE THREAD

**Issue by ycAbout** [BrkRaw/bruker#51]
For some of the bids output .json file, when the value of CogAtlasID is "Value was not specified", the bids validator raise
'.CogAtlasID should match format "uri" ' error. So does CogPOID.

This relates to #36, but that issue carries too much weight, I think put this as a separate issue would benefit users and make things more manageable.

**Comment by gdevenyi** [comment]
These are recommended in the context of fMRI task:
https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#fmri-task-information

Are they being included when the MRI is not labelled task? Otherwise, I think the requirement here is the json helper is supposed to be edited to provide the missing fields before the BIDS is generated.

**Comment by gdevenyi** [comment]
(This may be a documentation issue if it is only included in fMRI task, which is correct)

**Comment by ycAbout** [comment]
I checked a couple .json for non bold scans, it seems that they were not included (in our example dataset). In either case, I think a default value that passes the validator should be generated automatically if user did not specify any value. I will look into it.
It's also a good idea to mention it in documentation as well.

**Comment by dvm-shlee** [comment]
The CogAtlasID and CogPOID seems recommended not mandatory,
It may be resolved by updating

https://github.com/BrkRaw/bruker/blob/0d387c62d81f64ee712476b73795727c618028e2/brkraw/lib/reference.py#L220 

to be an empty string if this could work?

**Comment by ycAbout** [comment]
You have to put something like "https://www.cognitiveatlas.org/fillYourID" to make it work. I made a PR for it.
